import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import DeviceIntroBlock from "../components/DeviceIntroBlock/DeviceIntroBlock";
import UsecaseBlock from "../components/UsecaseBlock/UsecaseBlock";
import CreateIdealBlock from "../components/CreateIdealBlock/CreateIdealBlock";
import ExperienceBlock from "../components/ExperienceBlock/ExperienceBlock";
import HappyCustomer from "../components/HappyCustomer/HappyCustomer";
import SubscribeBlock from "../components/SubscribeBlock/SubscribeBlock";
import Footer from "../components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <DeviceIntroBlock />
      <UsecaseBlock />
      <CreateIdealBlock />
      <ExperienceBlock />
      <HappyCustomer />
      <SubscribeBlock />
      <Footer />
    </div>
  );
}
